site_name: Maixnor@WU
repo_url: https://github.com/maixnor/wu
edit_uri: edit/master/obsidian
docs_dir: obsidian
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
theme:
  name: material
  palette:
    primary: deep purple
  logo: assets/obsidian.png
  favicon: assets/obsidian.png
  custom_dir: obsidian/overrides
nav:
  - Overview: 'Index.md'
plugins:
  - search
  - redirects:
      redirect_maps:
