name: Deploy Obsidian Quartz

on:
  push:
    branches:
      - main  # Set your default branch here
      - quartz

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Quartz
      run: |
        npm install -g @quartz/cli

    - name: Build Static Site
      run: |
        quartz build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Specify your build directory

